name: GitHub Actions Each Branchs
on:
  push:
    branches:
      - dev-1
      - dev-2
jobs:
  Job-For-Dev-1:
    if: github.ref == 'refs/heads/dev-1'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job was triggered by a push to dev-1 branch."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "Running on dev-1 branch."

  Job-For-Dev-2:
    if: github.ref == 'refs/heads/dev-2'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job was triggered by a push to dev-2 branch."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "Running on dev-2 branch."
